### ISSUE TITLE
Basic Readme info

### ISSUE THREAD

**Issue by mattporritt** [catalyst/moodle-local_smartmedia#2]
Writing the Readme is going to be an ongoing but lets start with the basics
[ ] Write a brief plugin overview
[ ] add supported Moodle Versiosn (3.5+)
[ ] add install instructions
[ ] add setup instructions

Use: https://github.com/catalyst/moodle-fileconverter_librelambda or https://github.com/catalyst/moodle-auth_saml2 as a template

**Comment by mattporritt** [comment]
HI @tomdickman 
I can see that you've made a start here so I've pulled this into doing on the project baord, can you please update, this with what you've done, and make a PR for master?

**Comment by mattporritt** [comment]
Hi @tomdickman ,
I've merged in the changes from: issue #9 
a couple of quick things, change the copyright from me to Catalyst and put the pretty "developed by Catalyst" at the bottom (see auth_saml2) for example.
After that we'll call this one done and update the readme as we go

**Comment by tomdickman** [comment]
I mistakenly moved this to done, moving back, @mattporritt I will update in line with your comments:

> Hi @tomdickman ,
> I've merged in the changes from: issue #9
> a couple of quick things, change the copyright from me to Catalyst and put the pretty "developed by Catalyst" at the bottom (see auth_saml2) for example.
> After that we'll call this one done and update the readme as we go

**Comment by mattporritt** [comment]
I've made the final changes and merged into master
