### ISSUE TITLE
Privacy: missing privacy provider

### ISSUE THREAD

**Issue by tomdickman** [catalyst/moodle-local_smartmedia#69]
The Moodle Privacy API requires that all user data is declared in the privacy `provider` class for a plugin, in accordance with GPDR regulations. We need to create this class and identify within it what data in the plugin tables is user data.

**Comment by mattporritt** [comment]
I had a chat with Moodle HQ about this. We'll start with a privacy provider that provides data to an external service.
We'll like need to update the privacy provider as we add additional functionality. But right now we are not storing any user data.

**Comment by mattporritt** [comment]
merged
