### ISSUE TITLE
Conversion: MPEG-DASH and HLS transcoding jobs require a Playlist

### ISSUE THREAD

**Issue by tomdickman** [catalyst/moodle-local_smartmedia#85]
resolves #90 

When transcoding a file or multiple files into an MPEG-DASH or HLS output for adaptive media, the elastic transcoder requires additional parameters be passed to job.

We need to update the lamda function for transcoding to add in a `Segment Duration` parameter and `Playlist` parameter (containing at least `Master Playlist Name`, `Playlist Format` and `Outputs in Master Playlist`)

This information may need to be passed from Moodle as well, in a predicatable manner so we need to implement this in the metadata passed to the lamda.

**Comment by tomdickman** [comment]
Further investigation reveals that the Playlist requirement can be determined by the `Container` type or the Elastic Transcoder Preset, if it it `ts` or `fmp4` a Master Playlist is a requirement. https://docs.aws.amazon.com/elastictranscoder/latest/developerguide/job-settings.html#job-settings-playlist

**Comment by mattporritt** [comment]
@tomdickman issue #82 is also going to make our life easier. As the number and variety of transcoded presets are going to be limited
