### ISSUE TITLE
Conversion: Incompatible presets are included in metadata

### ISSUE THREAD

**Issue by tomdickman** [catalyst/moodle-local_smartmedia#94]
Conversions currently don't parse the presets to determine which ones are compatible with the media being transcoded, and instead send all presets in the metadata to S3, as a result the transcoder lambda is throwing errors (example: am mp3 file cannot be converted to an HLS Video and will throw an Error in Elastic Transcoder)

Need to amend conversion class to filter out presets which are not possible from metadata passed to S3 which is used by transcoder lambda

**Comment by tomdickman** [comment]
![transcoder_partial_fail](https://user-images.githubusercontent.com/24489417/64929150-8cf9fa00-d865-11e9-836c-5a622e8190c6.png)
Example of a failure on mp3 transcoding

**Comment by mattporritt** [comment]
merged
